### PR TITLE
qr support for etherscan sendRawTransaction, mobile responsiveness, checksumming 'to' address

### PR DESCRIPTION
**Pull request by zmitton**

### CODE REVIEW

**Comment by zmitton** [comment]
first of 3 updates. they will come each as 1 commit. feel free to review all at once at the end

**Comment by zmitton** [comment]
@christianlundkvist 
image

**Comment by christianlundkvist** [comment]
@zmitton

1. Would be cool if we can also expose the gasLimit in the UI

2. I noticed some weird things about the QR code, if you create a transaction and then change some stuff and create it again, the QR code gets smaller and smaller. It's also very blurry for some reason

**Comment by christianlundkvist** [comment]
Ok I'm merging this and will be making some upgrades :)

**Pull request merged**
