### PR TITLE
deleted duplicate icebox_html file and fixed path to lightwallet_min_js

### PR DESCRIPTION
**Pull request by zmitton**
So it took me a while to figure this out. much longer than I should have, but the base level icebox.html wasn't working because the lightwallet.min.js file had been moved. I realize that the icebox.html file in the  /dist/ directory is fine, but one of those files should go, and I see no reason to have the main file hidden away in a folder, so I deleted that one and changed the path from the other one.

### CODE REVIEW

**Comment by christianlundkvist** [comment]
This is how I had it to begin with, but I found it easier to just move the whole `dist` folder over to the offline machine, rather than having to reproduce the folder structure.

**Comment by christianlundkvist** [comment]
I'm going to close this, but thanks for the contribution!

**Comment by zmitton** [comment]
Ok, I guess the readme does say to use that file. Thanks for making icebox!

**Comment by zmitton** [comment]
I have a question. Since this is run in a browser, where is the key
actually being stored?

**Comment by christianlundkvist** [comment]
The key is held encrypted in memory when the browser is open. It is therefore very important that you write down your 12-word seed since the key will be removed if the browser window is shut down.

**Comment by zmitton** [comment]
thanks!

**Pull request closed without merging**
